<?php
// Variables
return [
  "app" => "ErpExtract",
  "creatorName" => "DSI KFC",
  "creatorUrl" => "https://dsi.grupokfc.com",
  "templateName" => "Portal de Extraccion de información SAP RISE",
  "templateNameShort" => "ErpExtract",
  "templateSuffix" => "ErpExtract",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Portal para extracción de información desde SAP Rise",
  "templateKeyword" => "SAP, Tablas, Rise, Odata",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
  "productPage" => "https://themeselection.com/item/sneat-dashboard-free-laravel/",
  "productPagePro" => "https://themeselection.com/item/sneat-dashboard-pro-laravel/",
  "support" => "https://github.com/themeselection/sneat-html-laravel-admin-template-free/issues",
  "moreThemes" => "https://themeselection.com/",
  "documentation" => "https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation",
  "repository" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free",
  "gitRepo" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free.git",
  "gitRepoAccess" => "https://tools.themeselection.com/github/github-access",
  "githubFreeUrl" => "https://github.com/themeselection",
  "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
  "twitterUrl" => "https://twitter.com/Theme_Selection",
  "githubUrl" => "https://github.com/themeselection",
  "dribbbleUrl" => "https://dribbble.com/themeselection",
  "instagramUrl" => "https://www.instagram.com/themeselection/"
];
